"""change points fields to decimal

Revision ID: 534b1ebbbd36
Revises: 3fed8ee40dd0
Create Date: 2025-08-01 11:00:30.956194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534b1ebbbd36'
down_revision = '3fed8ee40dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prize', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('redemption', schema=None) as batch_op:
        batch_op.alter_column('points_spent',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('redemption', schema=None) as batch_op:
        batch_op.alter_column('points_spent',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('prize', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
